### ISSUE TITLE
[Practitioner Guide]: Responsiveness

### ISSUE THREAD

**Issue by geekygirldawn** [chaoss/wg-data-science#19]
### Practitioner Guide Topic (1 - 3 words)

Responsiveness

### Primary Metrics (2 - 4 metrics)

Change Request Closure Ratio, Time to First Response, Time to Close

### Why is this topic important? How will this help people improve their open source project and / or community? Who will benefit from this guide?

Responsiveness metrics are important for new contributor recruitment and retention of existing contributors. Contributors can become discouraged when they don’t receive a timely and appropriate response to a contribution but can be encouraged when they get a quick and helpful resolution to their contribution. When projects are responsive, it can make people want to contribute more or continue contributing. Timely, thoughtful, and kind responses to contributors indicate that you appreciate their work.

Responsiveness can also impact overall project operations, especially regarding change requests (pull requests / merge requests). The longer a change request sits around without being merged, the more merge conflicts accumulate to the point where it may become too difficult or impossible to accept. Sometimes, a contribution may never be included due to incompatibilities, conflicts with overall project direction, or other considerations. In those cases, it’s better to let someone know in a kind and thoughtful manner why their contribution won’t be accepted rather than keep them guessing and increase their frustration with a lack of response. You can reduce technical debt, decrease maintainer workload, and improve contributor retention by being responsive and keeping up with contributions.

### How would you like to see this guide developed?

I have the experience and time available to write the first draft

### Additional Notes

This is already started. You can find the WIP document at https://docs.google.com/document/d/1bRe7m-kIr208H_MaubbU87QIJZJ18wc_g0mN_cEXO_c/edit

**Comment by geekygirldawn** [comment]
We have a solid [first version](https://docs.google.com/document/d/1bRe7m-kIr208H_MaubbU87QIJZJ18wc_g0mN_cEXO_c/edit) of this guide that people can continue to review.

**Comment by geekygirldawn** [comment]
This has been published. Future suggestions / can be made as PRs on https://github.com/chaoss/wg-data-science/blob/main/practitioner-guides/responsiveness.md

**Comment by voongc** [comment]
Here's an academic paper that can help support this: https://arxiv.org/pdf/2304.08426
