### ISSUE TITLE
[Project]: Event Location Inclusivity

### ISSUE THREAD

**Issue by geekygirldawn** [chaoss/wg-data-science#43]
### Project Name (1 - 3 words)

Event Location Inclusivity

### Description

OpenSSF DEI has been discussing how to make event locations more inclusive and I found that the CHAOSS community already beautifully created a [metric on event location inclusivity](https://chaoss.community/kb/metric-event-location-inclusivity/). Using data science, we would like to find out: Where are inclusive event location cities? Variables could include demographics and cost. Would anyone be interested in a small project based on this metric?

- Cost
- Public transportation availability
- AQI / air quality
- Population diversity
- Visa access

Note that we also have a [Project Scope Template doc](https://docs.google.com/document/d/13iLNDfqJ8nuwBGEyJuFutcT7KRNT6JwFrSlJN_5f4o4/edit) that you can use to think about the project details if you find it useful (not required).

### How would you like to be involved in this project?

I am interested in this project, but do not plan to work on it myself

### Additional Notes.

This is something that @voongc, @ElizabethN, and @sophia-IV have started working on. Do you have any docs you're using that you can link from this issue to help us track it?

**Comment by ElizabethN** [comment]
Our current working doc is [here](https://docs.google.com/document/d/1jKcHnjZjFwM5zXz1jKdtCiSwTdT-MAt9isSYhCIQSgA/edit). Thanks so much @geekygirldawn! ✨

**Comment by geekygirldawn** [comment]
@voongc @ElizabethN @sophia-IV - Since this has been moved to the DEI WG, should we close the issue here in the DS WG or keep it open?
